name: 10-Minute Scraper

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run script
        run: python check_free_rooms.py ${{ vars.FOXWOODS_CHECK_IN }}
        env:
          FOXWOODS_CONFIG: ${{ secrets.FOXWOODS_CONFIG }}